### ISSUE TITLE
as3.0的有吗？

### ISSUE THREAD

**Issue by micenote** [Mingyueyixi/DocDiy#1]
as3.0的有吗？

**Comment by Mingyueyixi** [comment]
今天我才用的。3.0也能用。原理一样。只是3.0得手动给一下路径。要不然自己改一下源码，给路径，编译一个新的

**Comment by micenote** [comment]
直接选择路径就可以了是吧？

**Comment by Mingyueyixi** [comment]
要用路径右边的按钮来选择。路径是user目录下的.Android studio3.0。直接改要挂掉，工具不完善。

**Comment by micenote** [comment]
我都不敢改了，你就弄个3.0的出来罢。

**Comment by Mingyueyixi** [comment]
3.0的android studio 已经修复这个毛病了。默认路径为本地文档，只要你下载过本地文档。它的配置就是对的。如果不对，你可以手动去C:/用户/.android studio3.0/config/options/jdk.table.xml ，将javadocPath 改掉目录为本地文档路径。或者删除掉这个文件，重开android studio3.0，他会自己配置。jdk.table.xml 中要修改的xml节点为：
`
<javadocPath>
          <root type="composite">
            <root type="simple" url="file://D:/Programing/Android/sdk/docs/reference" />
          </root>
        </javadocPath>
`

在之前的版本，就是这样配置的。没有本地doc，会配置成网络的路径。我当时出于源码更全面一点的考虑，这个工具配置成了源代码的路径。配了之后，快捷键就无法跳到浏览器查看本地文档。算是有所取舍。

**Comment by micenote** [comment]
好的，谢谢！
